version: "3.7"
services:
    app:
        container_name: api
        build:
            context: .
        ports:
            - "80:80"
        volumes:
            - "./:/var/www/html"
            - "/var/www/html/vendor/"
        networks:
            - default
    db:
        container_name: database
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: open_fact
        ports:
            - "27017:27017"
        networks:
            - default
